### ISSUE TITLE
Warning: Give up this dataset because at least one distance exceeds 20.00

### ISSUE THREAD

**Issue by HTaekOppa** [yongzhiyang2012/WGDdetector#2]
Hi WGDdetector

Hope this email finds you well.
While I was testing WGDdetector for our data (Allotetraploid genome = 3Gb size), I have bumped into a problem. 

FYI,
Computing environment: c5d.9xlarge in AWS
The executed script: See the attached file named “NbT2_run-c5d.9xlarge._Script.txt”.
The log file: See the attached file named “NBT2_run-c5d.9xlarge.txt”.

Q1. If you look at the log file, there are several warnings “Warning: Give up this dataset because at least one distance exceeds 20.00.”
Not sure whether this is a generic warning. Or did it affect on next stage analyses? What does that mean? 

Q2. Despite these warnings, the pipeline has got through the next stages, Hierarchical Clustering and Collecting final ks result for plot and comparing.
However, we could not find the pdf file, final.ks.distribution.list.pdf. 
Not sure whether the pipeline and analyses have been completed properly. 

What I am really after is to retrieve dS values and dS distributions (Fig. 2 in your paper) for our data. 

Any advice would be appreciated.

Regards,

[NbT2_run-c5d.9xlarge_Script.txt](https://github.com/yongzhiyang2012/WGDdetector/files/4094931/NbT2_run-c5d.9xlarge_Script.txt)
[NBT2_run-c5d.9xlarge.txt](https://github.com/yongzhiyang2012/WGDdetector/files/4094932/NBT2_run-c5d.9xlarge.txt)
Taek

**Comment by yongzhiyang2012** [comment]
Your command has no problem.
You can supply the zipped CDS and protein files for me to help us imporve our scripts.
